specVersion: 1.0.0
name: avail-indexer
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  Avail indexer project
repository: "https://github.com/availproject/avail-indexer"
schema:
  file: ./schema.graphql
network:
  # The genesis hash of the network (hash of block 0)
  # chainId: "0xb91746b45e0346cc2f815a520b9c6cb4d5c0902af848db0a80f85932d2e8276a" # Mainnet
  # chainId: "0xd3d2f3a3495dc597434a99d7d449ebad6616db45e4e4f178f31cc6fa14378b70" # Turing
  # chainId: "<local_chain_genesis_hash>"                                         # Local
  # chainId: "<local_chain_genesis_hash>"                                         # Local with Docker
  # endpoint:
  #   ["wss://mainnet-rpc.avail.so/ws"]                                           # Mainnet
  #   ["wss://turing-rpc.avail.so/ws"]                                            # Turing
  #   ["ws://127.0.0.1:9944"]                                                     # Local
  #   ["ws://host.docker.internal:9944"]                                          # Local with Docker
  
  # The genesis hash of the network (hash of block 0)
  chainId: "0xb91746b45e0346cc2f815a520b9c6cb4d5c0902af848db0a80f85932d2e8276a"
  endpoint:
    ["wss://mainnet-rpc.avail.so/ws"]
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
